### ISSUE TITLE
Uno Wifi Rev 2 SPI Library warning

### ISSUE THREAD

**Issue by tnjyoung** [arduino/ArduinoCore-megaavr#10]
I'm getting the following warning when verifying my code for the new Uno Wifi Rev 2:

WARNING: library SPI claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (megaavr) architecture(s).

I'm not using the SPI library, so I'm not sure where this is coming from (included in another library?).  I don't see an updated SPI library for the Uno Wifi Rev 2 in the online editor.  Is this something to be concerned with?

**Comment by facchinm** [comment]
Hi @tnjyoung ,
this has just been fixed in master by https://github.com/arduino/ArduinoCore-megaavr/pull/9 . 
As soon as we release an updated core the warning will disappear.
