### ISSUE TITLE
Issue with tone() on Arduino UNO Wifi

### ISSUE THREAD

**Issue by lemio** [arduino/ArduinoCore-megaavr#13]
This code wouldn't make a sound on a regular piezo, nor make a signal on the oscilloscope
```cpp
void setup() {
  pinMode(6, OUTPUT);
}

void loop() {
  delay(1000);
  tone(6,600);
  delay(100);
  noTone(6);
}
```
While this code does work:
```cpp
void setup() {
  pinMode(6, OUTPUT);
}

void loop() {
  tone(6,600);
  delay(100);
  noTone(6);
  delay(1000);
}
```

This code also works:
```cpp
void setup() {
  pinMode(6, OUTPUT);
}

void loop() {
  delay(1000);
  tone(6,600);
  tone(6,600);
  delay(100);
  noTone(6);
}
```

Would there be a way to fix it in the https://github.com/arduino/ArduinoCore-megaavr/blob/master/cores/arduino/Tone.cpp file? It seems like delay(x) leaves some timer in a state that tone can't deal with. Other functions like delayMicroseconds() seem to work with tone without any problems...

I use version 1.6.24 in the board manager, tried different Arduino UNO Wifi's and selecting ATMEGA328 register emulation doesn't influence the problem.

**Comment by facchinm** [comment]
Fixed by 76c9153, it was an issue with registers not being setup due to a missing `cli()`
