### ISSUE TITLE
Library Arduino_Uno_WiFi_Dev_Ed_Library claims to run on (avr) 

### ISSUE THREAD

**Issue by barend69** [arduino/ArduinoCore-megaavr#39]
Library Arduino_Uno_WiFi_Dev_Ed_Library claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (megaavr) architecture(s)

**Comment by per1234** [comment]
The Arduino_Uno_WiFi_Dev_Ed_Library is for the Arduino Uno WiFi. That library is of no use for the Arduino Uno WiFi Rev2. If you have an Arduino Uno WiFi Rev2, then you should be using the WiFiNINA library instead:
https://www.arduino.cc/en/Reference/WiFiNINA
