### ISSUE TITLE
[Nano Every] Incorrect RX/TX pin placement?

### ISSUE THREAD

**Issue by MCUdude** [arduino/ArduinoCore-megaavr#48]
I'm working on a pinout diagram for the Nano Every, since there doesn't exist one yet.
It turns out that there might be a hardware issue with the TXD1 and RXD1 pins. Why is the TX pin (digital pin 1, TXD1) placed as the first pin, and the RX pin (digital pin 0, RXD1) placed as the second pin?

Is this on purpose or just a hardware bug that's too late to fix?

<img width="529" alt="Skjermbilde 2019-08-19 19 34 34" src="https://user-images.githubusercontent.com/3238730/63286501-76896e80-c2b8-11e9-8618-d519f7a419f1.png">

**Comment by per1234** [comment]
It's on purpose. The Nano Every follows the pinout of the original Nano:
![A000005_featured_2](https://user-images.githubusercontent.com/8572152/63290777-09a1b480-c277-11e9-8179-675dc9a41b2f.jpg)

**Comment by MCUdude** [comment]
Well, that's just terrible research from my side... Thanks, @per1234!
