### ISSUE TITLE
Nano Every: analogRead(...) gives only 1023

### ISSUE THREAD

**Issue by RudolfAtHome** [arduino/ArduinoCore-megaavr#61]
Symptoms with 2 boards:
 - analogRead(A0) or analogRead(A1) gives only 1023
 - used references: INTERNAL1V1 and INTERNAL2V5
 - Voltage at pin = 0.120V - controlled with a multimeter
IDE 1.8.10 at Windows10 64 bit (runs well)
Package megaavr\1.8.5

**Comment by agdl** [comment]
Tried with a voltage 1/2 divider on 3.3V (10k Resistors) INTERNAL2V5 returns 672 that is right (1.65V)

**Comment by RudolfAtHome** [comment]
Sorry - my mistake, if works. My voltage control wars wrong (5V <> AIN, correct is GND <> AIN).
