### ISSUE TITLE
IDE "Port" is grayed

### ISSUE THREAD

**Issue by kklmn** [arduino/ArduinoCore-megaavr#69]
Hello,

After installing megaAVR 1.8.5 on IDE 1.8.12 in Windows 10 and 
selecting `Arduino Nano Every` the `Port` menu remains grayed.

Please advise.
Thank you!

**Comment by per1234** [comment]
Make sure the USB cable is completely plugged into both the Arduino board and the PC.

You may have a damaged/defective or charge-only USB cable. Try a different cable.

**Comment by kklmn** [comment]
Ah, shame on me, it was it indeed! Thank you!
